# Site
repository: albsha/albsha.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alban Shahaj
title: Software Developer and Data Analyst
email: shhkalb@gmail.com
website: https://albsha.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: albyshaka
github_username:  albsha
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: albyshaka
linkedin_username: alban-shahajoop
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#  icon: ont awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Alban and I'm a software developer and data analyst. My main role is to develop and maintain mainly client side applications (local and web apps) used for collecting data. I am also responsible for all the documentation, support and training provided to the various colleagues, external stackeholders and data providers. I started my career as software developer since 2017 just after my graduation in computer science.

  What I like more is: develop software and try to achive interesting goals, travel and discover new cultures as well as being able to talk with animals in a comprehensible language (who wants to help me :D).

content:
  - title: Software developer and data analyst # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bv Tech s.r.l
        link: https://www.bv-tech.it/it/
        # link_text: boringcompany.com
        sub_title: Software developer and data analyst
        caption: March 2019 - Present
        quote: >
          My main role is to work as consultant at the European Food Safety Authority (European organisation based in Parma, Italy). Here I am working for the Data department in which, my main role, is to develop, maintain and present client side application used from internal and external users. In addition I am also responsible for the maintainance of the various projects and the release of documentations and trainings.
        description: | # this will include new lines to allow paragraphs
          I am mainly a backend developer with few knowledge on the frontend implementation.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: albsha/albsha.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
